title: Filehoo Download Full Freeware Shareware Software Programs applications utilities tools portable apps
baseurl: "" # the subpath of your site, e.g. /blog
domain-name: www.filehoo.com
url: https://www.filehoo.com
enforce_ssl: /www.filehoo.com
keywords: >- # this means to ignore newlines until "description:"
  Filehoo, download, freeware, shareware, software, programs,
  screensavers, wallpapers, codecs, applications, utilities, drivers, games
description: >- # this means to ignore newlines until "author:"
  download, freeware, shareware, software, programs,
  screensavers, wallpapers, codecs, applications, utilities, drivers, games
author: Atilla Tanrikulu
environment: production
permalink: pretty
markdown: kramdown
highlighter: rouge
img: /assets/img
changefreq: monthly
priority: 0.5

disqus:
  shortname: filehoo-com
#google_analytics: UA-2498474-2

# Build settings

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - node_modules
  - lib
  - CNAME

collections:
  downloads:
    output: true
    permalink: /downloads/:path/
  categories:
    output: true
    permalink: /download-:path/
  tags:
    output: true
    permalink: /:path-downloads/
  letters:
    output: true
    permalink: /download-:path/
